bicycle/urls.py
from django.urls import path
from . import views

app_name='bicycle'
urlpatterns=[
    path('',views.bicycle, name="bicycle"),
]

introduction/urls.py
from django.urls import path
from . import views

app_name = "introduction"

urlpatterns = [
    path('', views.mise, name="mise"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('bicycle/', include('bicycle.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import new, create, main, show, update, delete

app_name = "posts" 

urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('/show/<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    ]

bicycle/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to = 'images/', null = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete= models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

bicycle/views.py
from django.shortcuts import render

# Create your views here.
def bicycle(request):
    return render(request, 'bicycle/bicycle.html')

introduction/views.py
from django.shortcuts import render

# Create your views here.
def mise(request):
    return render(request, 'introduction/mise.html')

myblog/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
# Create your views here.

def new(request):
    return render(request,'posts/new.html')

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        Post.objects.create(title=title, content=content, image = image) 
        user = request.user
        return redirect('posts:main')

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts': posts})

def show(request, id):
    post = Post.objects.get(pk=id)
    post.view_count +=1
    post.save()
    return render(request, 'posts/show.html', {'post': post})

def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('posts:show',post.id)
    return render(request, 'posts/update.html',{"post":post})

def delete(request, id):
    post = get_object_or_404(Post,pk=id)
    post.delete()
    return redirect("posts:main")

bicycle/templates/bicycle/bicycle.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <img class="img" src="{% static 'images/bic.png' %}" alt="이미지">
    <h1 class="t">따릉이 대여 현황</h1>
    <button onclick="q2()" type="button" class="btn btn-outline-dark b">업데이트</button>
    <table class="bicy">
        <thead>
            <tr>
            <td class="first cent">지역</td>
            <td class="second cent"> 거치대 수</td>
            <td class="third cent">현재 거치된 수</td>
            </tr>
        </thead>
        <tbody id="names_q2">
        </tbody>
    </table>
</div>
{% endblock %}

introduction/templates/introduction/mise.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
<img class="img" src="{% static 'images/img_0.png' %}" alt="이미지">
<h1 class="t">서울시 미세먼지 현황</h1>
<button onclick="q1()" type="button" class="btn btn-outline-dark b">업데이트</button>

<table>
    <thead>
        <tr>
            <td class="re cent">지역</td>
            <td class="re cent">지수</td>
            <td class="re cent">등급</td>
        </tr>
    </thead>
    <tbody id="names_q1">
    </tbody>
</table>
</div>
{% endblock %}

myblog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@500&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <script src="{% static 'js/project.js' %}"></script>
    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <img class="img_1" src="{% static 'images/seoul.png' %}" alt="이미지">
    <div id="carouselExampleIndicators" class="carousel slide mainimg" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'images/moon.png' %}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/night.png' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/lotte.png' %}" alt="Third slide">
          </div>
        </div>
      </div>

      <img class="mainimg_1" src="{% static 'images/map.png' %}" alt="이미지">
</div>
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">서울특별시</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'introduction:mise' %}">미세먼지</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bicycle:bicycle' %}">따릉이</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">시민게시판</a>
        </li>
      </ul>

      <ul class="nav navbar-nav ">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">Account</a>
          <div class="dropdown-menu">
            {% if user.is_authenticated %} {# 유저가 로그인 중이면 #}
            <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
            <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
{% if user.is_authenticated %}
<div class="container">
    <h1>게시판</h1>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p>{{ post.created_at }}</p>
                    <p>조회수: {{post.view_count}}</p>
                    <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %} </div>
    <a class="nav-link" href="{% url 'posts:new' %}">글쓰기</a>
    {% else %}
      <h3>로그인 후 이용이 가능합니다.</h3>
      <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
      <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
</div>
{% endblock %}s

posts/templates/posts/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %} <div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>글 제목</label>
            <input type="text" class="form-control" name="title"> </div>
        <div class="form-group">
            <label>글 내용</label>
            <textarea class="form-control" name="content"></textarea>
        </div>
        <input type="file", name="image">
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>상세보기 페이지</h1>
<h3>글 제목 : {{ post.title }} </h3><br>
<h3>글 내용 : {{ post.content }} </h3><br>
{% if post.user %}
<h3>작성자 : {{ post.user }} </h3><br>
{% else %}
<h3>작성자 : 알 수 없음</h3><br>
{% endif %}
<h3>작성 시각 : {{ post.created_at }} </h3><br> 
<h3>수정 시각 : {{ post.updated_at }} </h3><br> 
<h3>조회수: {{post.view_count}}</h3><br>

{% if post.image %}
    <img src="{{post.image.url}}">
{% endif %}
{% if user == post.user %}
<a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
<a href="{% url 'posts:delete' post.pk %}" class="btn btn-danger">삭제하기</a>
{% endif %}
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1> 수정하기 </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>글 제목</label>
            <input type="text" class="form-control" name="title" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label>글 내용</label>
            <textarea class="form-control" name="content"> {{ post.content }} </textarea>
        </div>
        <input type="file", name="image">
        <input type="submit" value="글 수정" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}